### ISSUE TITLE
Error w/ Lita 4.0

### ISSUE THREAD

**Issue by johntdyer** [change/lita-hangouts#2]
I'm trying this out w/ Lita 4.0 and getting the following:

```
 # jdyer at retina.dyer in ~/Projects/tropo_projects/tropo-bot-lita [14:19:53]
$ lita
[2015-04-25 18:20:14 UTC] FATAL: Lita configuration file could not be processed. The exception was:
undefined method `hangouts' for #<Lita::Configuration:0x007fe8f44f9cc0>
Full backtrace:
/Users/jdyer/Projects/tropo_projects/tropo-bot-lita/lita_config.rb:49:in `block in <top (required)>'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/lib/lita/registry.rb:17:in `configure'
/Users/jdyer/Projects/tropo_projects/tropo-bot-lita/lita_config.rb:1:in `<top (required)>'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/lib/lita/configuration_builder.rb:49:in `load'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/lib/lita/configuration_builder.rb:49:in `load_user_config'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/lib/lita.rb:75:in `run'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/lib/lita/cli.rb:77:in `start'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/jdyer/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/lita-4.3.2/bin/lita:6:in `<top (required)>'
/Users/jdyer/.rbenv/versions/2.1.3/bin/lita:23:in `load'
/Users/jdyer/.rbenv/versions/2.1.3/bin/lita:23:in `<main>'
```

my config contains 

```
config.handlers.hangouts.namespace = "tropo"
```

**Comment by johntdyer** [comment]
I was able to get it working w/ the following in my config

```
config.handlers.hangout.domain = "tropo"
```

I guess the docs are incorrect?

**Comment by kylev** [comment]
This is not the droid you're looking for. It seems there is a work-alike with a slightly different name: https://github.com/brodock/lita-hangout
